OAuth2\ServerBundle\Entity\ClientPublicKey:
    type: entity
    table: oauth_client_public_key
    id:
        client_id:
            type:       string
            length:     50
            column:     id
    fields:
        publicKey:
            type:       text
            column:     public_key
    oneToOne:
      client:
        targetEntity: OAuth2\ServerBundle\Entity\Client
        joinColumn:
          name: client_id
          referencedColumnName: client_id
          onDelete: CASCADE
          onUpdate: CASCADE
    lifecycleCallbacks: {  }
